name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: './DetectiveNet.Sdk/DetectiveNet.Sdk.sln'
      LIBRARY: './DetectiveNet.Sdk/DetectiveNet.Sdk.csproj'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Build Version
      run: |
        Import-Module .\pipeline\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x.x

    - name: Build
      run: dotnet publish $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION
      
    - name: Package
      run: dotnet pack $LIBRARY 

    - name: Publish
      # if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
